version: '3'

services:
  ansible:
    container_name: ansible 
    build: docker/ansible
    tty: true
    working_dir: "/var/data"
    volumes:
      - ./ansible:/var/data
  mysql:
    container_name: mysql
    build: docker/target
    tty: true
    privileged: true
    ports:
      - "3306"
  wordpress:
    container_name: wordpress
    build: docker/target
    tty: true
    privileged: true
    ports:
      - "8000:80"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306

